### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by henryharan** [pwndoc/pwndoc#1]
what is the login?

**Comment by yeln4ts** [comment]
When no users are in the database, itl will ask you to create the first user that will be admin of the application.
If you don't see the registration form, it may be because there is a connection issue with the backend. You can verify it by accessing https://localhost:4242/api/users/init
Also when using firefox you have to add a certificate exception for the backend if you are using the self generated certificate.

**Comment by bbeamer** [comment]
Hello, I am trying to recover my admin password, as it looks like the last one I set is not working ! 
Also, I have no clues why the initialisation request (to the api path) [https://localhost:4242/api/users/init](url) is not working : it gives the following message : `{"status":"success","datas":false}` 

Any ideas ?
