### ISSUE TITLE
Concept of reviewers and report reviews

### ISSUE THREAD

**Issue by lm-sec** [pwndoc/pwndoc#108]
It could be nice to integrate the concept of reviewers and report reviews in the application. 

The feature may include: 
- Add a reviewer role, inheriting privileges from user, but with the addition of the "report approval" privilege
- A user cannot, by default, approve a report
- A reviewer cannot approve his own report
-  A reviewer can only approve a report once
- Adding a toggle on the admin panel to enable "mandatory review" of reports
- Adding a text box or drop down that lets the admin set the smallest number of approvals by reviewers required for a report to be "approved"
- A non-"approved" report, when "mandatory review" is toggled on, cannot be downloaded
- An "approved" report can be downloaded 

That way, it would be possible to have a junior pentester with the user role create a report but not review any as well as to have more senior pentesters create and review reports. It would add support in the tool for a report review process, often in place in businesses.

**Comment by yeln4ts** [comment]
Yes it would be nice and I had thought about this but it would need the possibility to add comments for each field in order to be really useful.

**Comment by lm-sec** [comment]
The possibility to add comments would, for sure, bring the feature to the next level. 

We could maybe do it in two iterations if needed, as it is a lot of changes. Initially go without and assume that the people working together have other means to communicate and then, in a second iteration, add the possibility to leave comments to make a better workflow.

I am sure the idea still needs to be perfected, but the feature looks important in my opinion.

**Comment by lm-sec** [comment]
FYI I am working on it, I have a first version almost done

**Comment by lm-sec** [comment]
I feel like it is more about code maintainability? Like it is easier and standardised to import a mongoose model and get configs than having to specify the file path to your settings file on the FS every time you need them? It also comes with the advantage that you can fully rebuild the app from a mongo data backup, even the settings. 

For the portability convenience, it would still be possible, as the default settings would still be set in that file, so you would keep that behaviour, unless you edit it dynamically and then want to export these new settings that would be set in database and not in the file. 

I could easily add some buttons in the settings page though that do the following: 
- Save --> saves the new settings in the database
- Restore default --> Sets the settings in the database to the content of the app-settings.json file
- Set new default --> Sets the content of the app-settings.json file to the current settings in database

That way, there would be no loss of portability

I was also thinking of regrouping the cvss_colors in app-settings.xml as they both concern the report output, and make it possible to edit them dynamically through the UI too.

**Comment by yeln4ts** [comment]
I don't think it would impact the maintainability since the file path is always relative to the basedir. Maybe it would be a better idea to define it globally the same as basedir since it will be potentially used from anywhere and it would solve your problematic.

Adding cvss_colors to the settings: 👍 

Also could you describe what you are working on with reviews ? like what functionalities and all ? Did you went through all the features you mentioned in your first message ? Because I have comments on some points

**Comment by lm-sec** [comment]
For the settings storage: 
A global variable would indeed solve this problem. I think that I still have a preference for mongo for its built-in type validation and the fact that right now mongo is everywhere in the app but not fs, it feels a bit weird to me to use a second way to store JSON objects while mongo does it already. In the end though, it mostly comes down to which line you want in several spots in the code:

var settings = await Settings.getSettings();
 or 
var settings = JSON.parse(fs.readFileSync(`${__basedir}/app-settings.json`)); 

I will do as you decide on that part, just let me know. 

For the incoming PR: 
What I have so far: 

- Add a reviewer role, inheriting privileges from user, but with the addition of the "report approval" privilege --> done
- A user cannot, by default, approve a report --> done
- A reviewer cannot approve his own report --> done
- A reviewer can only approve a report once --> done
- Adding a toggle on the admin panel to enable "mandatory review" of reports --> done, it is a setting
- Adding a text box or drop down that lets the admin set the smallest number of approvals by reviewers required for a report to be "approved" --> done as a setting with a number input field
- A non-"approved" report, when "mandatory review" is toggled on, cannot be downloaded --> done
- An "approved" report can be downloaded --> done

What was also added: 
- A setting to decide if an audit that is modified after his approvals stays approved
- Comments for audit reviews are well on the way in another branch, but I dont have pictures for that yet
- A reviewer field in which an audit collaborator or creator can add a reviewer (much like adding a collaborator)
- UI feedback in the list for approved audits
- A user can mark an audit as ready for review, giving UI feedback in the audit list 
- A reviewer can filter the audit list on audits that are marked as ready for review

Here are some previews of what I have.

What I suggest for the configs (minus the cvss colors that are not there yet):
![Screenshot from 2021-06-16 13-02-35](https://user-images.githubusercontent.com/21041333/122276633-fbdd0a80-ceb2-11eb-8892-dc8fdb6f96c0.png)

A user seeing his 4 audits: 
![Screenshot from 2021-06-16 14-41-12](https://user-images.githubusercontent.com/21041333/122276738-1a430600-ceb3-11eb-8a8c-923b67813f97.png)

A reviewer seeing the audits for which he is assigned: 
![Screenshot from 2021-06-16 14-41-32](https://user-images.githubusercontent.com/21041333/122276832-2fb83000-ceb3-11eb-8fa3-8276931cfcf5.png)

A user seeing an audit in progress: 
![Screenshot from 2021-06-16 14-42-01](https://user-images.githubusercontent.com/21041333/122276928-4c546800-ceb3-11eb-807a-6a7aa667f5f8.png)

A reviewer seeing an audit ready for review: 
![Screenshot from 2021-06-16 14-41-43](https://user-images.githubusercontent.com/21041333/122276965-5a09ed80-ceb3-11eb-8f5f-83a45b9083df.png)

It is hard to really list all that changed out of the blue without having you try it. Let me know what you think and you concerns, I am sure things can still be improved. If you clone my branch right now, the settings are not in the state of the screenshot, but the other things should work properly.

**Comment by lm-sec** [comment]
I discussed it with a friend and he raised another good point that I thought I should bring to your attention, even though it is unlikely to happen at the scale of this application. 

Using a file to store the settings can result in conflicts while trying to access it. If someone tries to, for instance, edit the configuration at the same time as someone trying to read settings (or any instance of reading the configs, which will become more and more likely as we use them more), it would block at OS level and lead to hard to reproduce timing bugs. 

Again, it is unlikely at the scale of this application, but it seems unnecessary.

**Comment by yeln4ts** [comment]
Thank you I checked it out quickly and it's really really nice 👍 

File access is a good point, I didn't thought about it so let's go with the database settings but with the possibility to import/export settings to a json file (file upload / file download)

There are lots of new stuff, I didn't test everything thoroughly but here are my thoughts from what I could test:

- Reviewer role should not be added by default, instead leave it free to name it and attribute custom privileges in roles.json.
(ex: Since the current reviewer role inherits from user permissions it can only access its own audits, so if you add a user as reviewer that has no access to the audit he wont be able to review it)
- I would add username(s) of reviewers that approved the Audit somewhere (maybe in the tooltip: "Audit is approved by ...")
- In the same spirit, if mandatory review is enabled with multiple reviewers needed, there should be a visual hint somewhere of how many approbations there are left to be done and which user already approved.
- Maybe remove editing when submitted for review so that the audit is freezed until approved. (but keep the ability to remove submission).
- The submit / review buttons are only present on the “General” section but I think it would be a better UX to have it accessible from anywhere. I would maybe put it in the sidebar, either on top or at the bottom.
- A user with “audits:review-all” and “audits:update-all” privileges (ex: admin) can update and save Audit before approving it. Also in this specific case the state of both isEditing and isReviewing would be true but it should be either one or the other.
- In Audits you put everything in readonly if user don't have update rights but there are some custom fields that are not in readonly state though (only editor seems to be readonly). You can try to add “Select” or “Checkbox” to test.
- Maybe remove the “Propose Creation / Update in Vulnerability Database” button too.
- In the settings I would add the option to enable/disable reviews so that when disabled it does not impact the GUI in the Audits section (thinking of users that would'nt want to use that functionality)
- The ready for review should also filter audits that you cannot review. And while at it I thought maybe a filter for reviewed Audits only (but that is starting to be a lot of filters 😛 )
- When Audit is approved the “Remove Submission” button is still there if user access its audit. The possibility to submit for a review should be allowed only if the audit is not approved yet.

**Comment by lm-sec** [comment]
Hi, I took note of your comments! I think they would be great addition, thank you for your feedback. 

I have questions on two points, otherwise, we are already started implementing the others. For instance, I just pushed the fully functioning and finished settings page, I hope you'll like it. I refactored a bit what we already had for better vuejs / quasar usage.  I also tried to make the best UX possible and to make it coherent with other pages as best as I could. 

So here are the questions: 
- A user with “audits:review-all” and “audits:update-all” privileges (ex: admin) can update and save Audit before approving it. Also in this specific case the state of both isEditing and isReviewing would be true but it should be either one or the other. 

I agree with you, it is quite an awkward situation to have someone with update-all and review-all being able to do both. However, I did not find a way to prevent such behaviour without starting to track every audit change. Another way that I just thought of, much easier, could be to add a user as a collaborator every time they update an audit in any way, even if they try to remove themselves from the collaborators. That way, another user would have to remove them for them to not be in the collaborators anymore. Would that behaviour work with you? 

Also, to prevent people from being able to edit and review at the same time, would you be comfortable with an audit not being able to be approved without it being marked as ready for review? That way, a reviewer added in an audit would be in an implicit "read-only" mode until the audit is marked as ready for review. Only then would he be able to approve it. 

- Maybe remove the “Propose Creation / Update in Vulnerability Database” button too.

It is still there because I thought that a reviewer would often be well placed to know if a well written finding would be a great addition to the vulnerability database. If you want it gone though, I do not mind, I can remove it. 

Thanks a lot for taking the time to try it and for the great comments!

**Comment by lm-sec** [comment]
Many updates were done to the branch. I migrated from weird booleans that worked in the beggining but were getting really messy to a state machine pattern. The state machine respects the following graph on the front-end audit edit page. The actual state of the audit is much simpler and is represented by the column names in the graph. Using the graph, it is really easy to know in which state your UI element should show and implement the condition. 

Here is the graph: 
![image](https://user-images.githubusercontent.com/21041333/122937452-ff074900-d33f-11eb-8f50-91217889ffdd.png)

For the new buttons, I went for icon buttons with tool tips in the top bar so they are available everywhere while editing. Here, an admin can remove the ready for review state of the report and remove his approval. Removing the ready for review state will remove his approval, like described in the graph: 
![image](https://user-images.githubusercontent.com/21041333/122940751-bf8e2c00-d342-11eb-94c2-d65b0ab5f365.png)

For the status of the review process, we went for tool tips on the status icon next to the name. The tooltip describes the current state, how many approvals are still needed for the review and who already approved:  
![image](https://user-images.githubusercontent.com/21041333/122940868-dc2a6400-d342-11eb-9ca5-2b5e1b838f2a.png)

We are almost done implementing all your comments, we only have "enable/disable reviews so that when disabled it does not impact the GUI in the Audits section" left to do. 

We also have the admin user that can edit and approve as an issue, but I am sill waiting for your feedback on that one. Maybe what we want is to let the people with review rights review their own report, and a business with stricter rules could always require two reviews before the approved state. It comes with the issue that an audit done by two people with review rights could be approved without a third party review, but maybe that is ok. 

Let me know which way you want to go on that issue.

**Comment by yeln4ts** [comment]
Great job can't wait to test it out.
Regarding the last issue with users having "reviews-all" and "updates-all" I didn't find a good simple solution as it would either prevent them from editing all audits or prevent them to review all audits. And I think the solution you proposed would work but it would be kind of weird.
So let's leave it as is, "with great power comes great responsibility"
