### ISSUE TITLE
[Question] Languages?

### ISSUE THREAD

**Issue by noraj** [pwndoc/pwndoc#12]
I saw this message

![image](https://user-images.githubusercontent.com/16578570/91662252-759d3680-eae1-11ea-8a5a-f778cefc7850.png)

So I went to the section and tried to add a new lang:

![image](https://user-images.githubusercontent.com/16578570/91662268-8fd71480-eae1-11ea-83b1-1dea46aed6b8.png)

but it seems it's not the expected format? By the way was is expected in locale? Like linux locals in /etc/locale.conf?

Unfortunately the wiki page is void https://github.com/pwndoc/pwndoc/wiki/Custom-Data

I finally was able to add those, I don't know if it's correct but maybe a help tooltip & filling the wiki would be helpful.

![image](https://user-images.githubusercontent.com/16578570/91662305-d75da080-eae1-11ea-98d4-55c0f37adbff.png)

If I can have write access to the wiki I could help fill it. The best would be to have a staticgen doc tool stored in the repo so anyone could PR.

**Comment by Hax0rG1rl** [comment]
I did this. Don't know if is aligned with what is actually expected. 

![image](https://user-images.githubusercontent.com/3704868/91673287-915b1800-eb87-11ea-8b2e-14bd7d1ad947.png)

**Comment by yeln4ts** [comment]
I just started the wiki so it's a little empty now but I plan to have it detailed enough in the near future (this month).
For languages the Language parameter will be the displayed name that you'll see in the application and the locale is what'll be used for the DB so it's not really important what you name it since you'll only have one English language
Me I use English -> en, French -> fr
