### ISSUE TITLE
Custom Sections don't work

### ISSUE THREAD

**Issue by nobox910** [pwndoc/pwndoc#134]
Hi,
I can not generate a report which contains audit custom sections  as the image below:
<img width="1680" alt="2021-06-07_20-10-00" src="https://user-images.githubusercontent.com/58721688/121022736-cfe3ca00-c7cc-11eb-834b-494b84fd1061.png">

 Could you please help me with how to fix it?

**Comment by yeln4ts** [comment]
Thank you I need to update the documentation for this because Custom Sections handling changed.
Before: Custom Sections had only 1 editor field
Now: Custom Sections consist of multiple custom Fields

For the example let's say we have one section called cleanup (section_field: cleanup) and 2 custom Fields: `cleanup (input)` and `additional (html editor)`
The resulting data used by the docx generator would be:
```
{
...
cleanup: 
  {
    cleanup: "cleanupcleanupcleanup...",
    additional: [{text: htmlParagraph, images: []}]
  }
}
```
So for your use case, since you are only using an input you should use in your template:
```
{cleanup.cleanup}
```

And if you want tu use an html editor instead of the input:
```
{#cleanup.cleanup}
{@text | convertHTML}
        {#images}
        {%image}
        Image 1 - {caption}
        {/images}
{/cleanup.cleanup}
```

**Comment by nobox910** [comment]
Great, It worked. Thank you very much!
