### ISSUE TITLE
[New Features] Note, Charts, Security Tools, Retest Status

### ISSUE THREAD

**Issue by tamquanminh** [pwndoc/pwndoc#14]
<img width="1680" alt="2020-08-31_12-45-17" src="https://user-images.githubusercontent.com/58721688/91686914-b3a16580-eb88-11ea-8e77-326c718cdde4.png">
<img width="1680" alt="2020-08-31_12-45-38" src="https://user-images.githubusercontent.com/58721688/91686923-b8661980-eb88-11ea-9199-f8613cad81dd.png">
<img width="1239" alt="2020-08-31_12-56-02" src="https://user-images.githubusercontent.com/58721688/91687213-6a054a80-eb89-11ea-9ad3-70daccc498fb.png">
<img width="1685" alt="2020-08-31_12-48-39" src="https://user-images.githubusercontent.com/58721688/91686925-b9974680-eb88-11ea-8807-b82cbd429573.png">
<img width="1680" alt="2020-08-31_12-48-58" src="https://user-images.githubusercontent.com/58721688/91686929-ba2fdd00-eb88-11ea-9562-a33039c61ef3.png">
<img width="1680" alt="2020-08-31_12-53-05" src="https://user-images.githubusercontent.com/58721688/91687010-f6fbd400-eb88-11ea-959c-842812580d86.png">

**Comment by yeln4ts** [comment]
Charts is something I thought about implementing but have to check if it can be used with the docx template engine or maybe have to convert it to an image before. It's in my pipeline and will see if it can be implemented.

I thought about having Notes but I'm not sure it would be useful since everyone has its own way of taking notes. But you can have it anyway by creating a custom Section called Notes if you want.

Same goes for Security tools, everyone has their own habits regarding tools they use and I dont' think this section would be really used.

Retest Status functionality would be interesting if the goal was to track and monitor your vulnerabilities for risk analysis but it's not exactly why it was designed. Create an audit type «retest» and then compare both reports after completing the retest is more the idea that I think would be used.

**Comment by BetaMaxHeadroom** [comment]
Hi, can you please share this template? This looks beautiful.
