### ISSUE TITLE
Findings numbering

### ISSUE THREAD

**Issue by Tim-Conrad** [pwndoc/pwndoc#147]
The numbering of the findings seems to be mixed up after document generation on the newest release. Might be something that I created and deleted issues while writing the report.

**Comment by sh0reline** [comment]
For me the first finding starts at 002, instead of 1.

**Comment by m6sec** [comment]
At the moment the id is determined once an issue is created/associated with an audit. The id is then incremented with each new finding.

The pro of this is that as soon as one discovered an issue a reference can be handed to out to the client/developers/.

The con is that one tends to end up with an unordered list of ids, since issues in the report are sorted by severity.

In the end I think it is a design choice, but I'd also welcome an option to rename/resort ids by severity. Maybe an additional setting somewhere that allows to switch between static / dynamic issue ids?

**Comment by BetaMaxHeadroom** [comment]
This issue is a rough one for me. I was hoping to generate a table for each vulnerability. The top cell/row in this table has the text 'FINDING 01', 'FINDING 02', and so on for each finding. Has anyone attempted using a macro as a workaround? In an attempt to explain what I am thinking, I will do my best to create a table in this comment. Please forgive me for how terrible this will look. I am considering generating a table to be used solely for this one purpose. It will look something like:

| Severity  | CVSSv3 | Vulnerability Name  |
| ------------- | ------------- | ------------- |
| {#findings}{cvssSeverity} | {cvssScore} | {title}{/findings} |

The (admittedly poor) table above will use the current implementation of the tool to create a table that sorts findings from highest to lowest CVSSv3 score. There is certainly a possibility that I am wrong with this logic. However, if this is the way that the tool functions, would anyone know how to write a macro that can take the existing table, add a new column, and then add a comment of 'FINDING *' to the corresponding cell? Something like:

| Reference    | Severity  | CVSSv3 | Vulnerability Name  |
| -----------    | ------------- | ------------- | ------------- |
| FINDING 01 | {#findings}{cvssSeverity} | {cvssScore} | {title}{/findings} |
| FINDING 02 | {#findings}{cvssSeverity} | {cvssScore} | {title}{/findings} |
| FINDING 03 | {#findings}{cvssSeverity} | {cvssScore} | {title}{/findings} |

Then, if that is possible, I will probably need to create another macro that will take the values from the newly created column, and push that to the table that my QA team came up with (because they will not budge on changing the template). 

I am not very good at this. If anyone wants to work with me, I will do my best to help where I can.

**Comment by get-fooby** [comment]
First make a template table like this:
Reference | Severity | CVSSv3 | Vulnerability Name
-- | -- | -- | --
{#findings}FINDING 01 | {cvssSeverity} | {cvssScore} | {title}{/findings}

In Word delete the 01 and click Insert, then Quick Parts, choose Field...
Find Seq in the list and select this, in the Field Properties box, under Field Codes ensure it says `SEQ FINDING` or instead of FINDING any other word you want. 

When the table loops, adding the rows, it will also add a new SEQ number to the row each time. Control-A and F9 and it will refresh the page.

Note, adding a new finding above this in severity will result in finding IDs applied to the wrong finding (an easy manual fix in Word, easy, but time consuming)

The alternate is adding a custom value to Audit Finding of Input and setting this as the sort value, and adding this as an export value to the final report.

**Comment by sl4cky** [comment]
It can be done by using a customized numbered list in the table. I had the same problem and solved it like that.

**Comment by sl4cky** [comment]
This is an attached example of it: 
![image](https://user-images.githubusercontent.com/13188087/149755857-5d7c8f38-814f-424f-953a-047551e35d84.png)

**Comment by BetaMaxHeadroom** [comment]
I didn't realize that you all had supported me. Thank you all so much. I think there was something up with the template I was using because nothing was working. Then there was a complete redesign of that template, and the customized numbered list works on the new template.
