### ISSUE TITLE
Documentation for Custom Fields and Sections?

### ISSUE THREAD

**Issue by katatafish5** [pwndoc/pwndoc#148]
Hi

Having trouble updating the template to be able to call the custom fields and the custom sections. 

![image](https://user-images.githubusercontent.com/44723589/124069389-6ed3ad00-da7f-11eb-823f-28790d658ff3.png)

For example, i've added a custom field called "Proposal" under the Audit General section that I want to display. Similarly to the custom fields with an editor field.
I can see the json version of the data but unsure which field to call in the docx template:
![image](https://user-images.githubusercontent.com/44723589/124080967-4d2df200-da8e-11eb-95b0-edff0c904e6a.png)

I've used an earlier version of PwnDoc and the online documentation appears to be referring to that version.

Thanks

**Comment by Fopje** [comment]
The label, in your example "proposal" can be used in the template. ( #146 )

**Comment by yeln4ts** [comment]
Yes you have to use the label in lower case + strip spaces: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=findings

**Comment by katatafish5** [comment]
Thanks for all the assistance. 
For those who had the same issue as me. 

Custom Fields with 'Input' Types can be referred to via the label name (just ensure it's all lowercase and no spaces) using:
{labelname}

Custom Fields with 'Editor' Types can be referred to using the format below:

{-w:p labelname}
{@text | convertHTML}
        {#images}
        {%image}
        {caption}
        {/images}
{/labelname}


Custom Sections with Custom fields set with 'editor' types can be referred using the Custom Section Name + Label Name: 

{-w:p sectionname.labelname}
{@text | convertHTML}
        {#images}
        {%image}
        {caption}
        {/images}
{/sectionname.labelname}

So if I were to have a Section called 'recon' and created a field called 'details', I would refer to it as follows:
{-w:p recon.details}
{@text | convertHTML}
        {#images}
        {%image}
        {caption}
        {/images}
{/recon.details}

![image](https://user-images.githubusercontent.com/44723589/125576521-ace477c0-83c4-4ea6-ba5f-04ffb3831aa3.png)

![image](https://user-images.githubusercontent.com/44723589/125576449-40ce14b3-f825-4308-adb3-e2b1f062171e.png)


Hope this can help someone down the track.

**Comment by BetaMaxHeadroom** [comment]
@katatafish5, thank you for doing this. However, I am still having an issue. I just wanted to run this by you to see if there is an issue on my end, or if there is an issue with my install, possibly. Here are the steps that I run as admin in the dev environment:

 1. As admin, create a new vulnerability category named "socialengineering" on localhost:8081
 2. Using the website, create a new custom field where "view = audit finding", "category = socialengineering", "component = input", and "label = emails-sent"
 3. click 'add' and then click 'save'
 4. click vulnerabilities at the top of the page, and create a new vulnerability titled "Phishing" with the category "socialengineering"
 5. Create a template with both {emails-sent} as a field literally anywhere, and {#findings}{emails-sent}{/findings}. Then, add that template through the app. 
 6. Create a new audit named "test-phishing", use the template just mentioned, add vulnerability "Phishing", and enter "10" in the "emails-sent" text field.
 7. Generate report.

I should clarify that I have not added/modified/edited anything directly in the backend, and I have not restarted the docker container. I am attempting to add the custom fields directly through the web interface. When the report is generated, I get the number '0' instead of '10' for both entries. 

- Can you please let me know if there is a step that I am missing? 
- Am I supposed to be making changes to files directly in a text editor?
- If you have a YouTube channel, and walk me through this, I will like, comment, and subscribe to every video you have. 
- Thank you in advance. I really appreciate it.

**Comment by yeln4ts** [comment]
In your docx template try using `{#findings}{emails_sent}{/findings}`
I have to update the documentation and/or add hints in the GUI because the label is lowercased, strip spaced and other stuff is replaced by `_`
Here is the transformation applied: `label.toLowerCase()).replace(/\s/g, '').replace(/[^\w]/g, '_')`

**Comment by BetaMaxHeadroom** [comment]
> In your docx template try using `{#findings}{emails_sent}{/findings}`
> I have to update the documentation and/or add hints in the GUI because the label is lowercased, strip spaced and other stuff is replaced by `_`
> Here is the transformation applied: `label.toLowerCase()).replace(/\s/g, '').replace(/[^\w]/g, '_')`

You are what dreams must be made out of. Thank you so much. I can't thank you enough.
