### ISSUE TITLE
Service pwndoc-backend failed to build

### ISSUE THREAD

**Issue by emilyanncr** [pwndoc/pwndoc#152]
....and straight away get an error
Service 'pwndoc-backend' failed to build: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority.
I tried googling the error but quickly feel deep into a hole

Jesus I've yet to come across a single pentest report generator that **actually** builds successfully.  

Using latest version of Kali Linux.
Replies and assistance appreciated.

**Comment by lm-sec** [comment]
Did you follow the documentation here: https://pwndoc.github.io/pwndoc/#/installation

Did you try to build it for development or for production?

Did you use the release? https://github.com/pwndoc/pwndoc/releases/tag/v0.3.0

Your bug sounds like you have trouble getting something from the docker registry because the certificate is not recognised. If it is while trying to get the initial alpine image (FROM node:lts-alpine), this is likely not something that pwndoc controls and would likely be related to either your machine not recognizing the issuer of the certificate, your network intercepting and decrypting the traffic somewhere (happens sometimes in enterprise networks) or the docker registry having an invalid certificate (unlikely, but I guess it could happen). 

If you had any more details, like a full log, it could help!

**Comment by NamrataSP** [comment]
Hi @emilyanncr,

Faced the same issue where I couldn't render pwndoc due to some backend problem. 
https://github.com/pwndoc/pwndoc/issues/155 --> Refer to this closed issue. 
Hope this helps.
