### ISSUE TITLE
Multi-lang of dynamic field

### ISSUE THREAD

**Issue by noraj** [pwndoc/pwndoc#16]
For example the CVSS severity or other CVSS criterias will be generated dynamically but will always be generated in English.
So having a translation section in Data would be welcome to allow us to translate all dynamic value used bu PwnDoc into another language. Or maybe instead of doing it in the WebUI having a JSON or YML file with all translation (1 file per language) could be nice so the community could translate all those + the WebUI terms.

**Comment by yeln4ts** [comment]
If I understand correctly you are talking about having translation on one part for the WebGUI and on the other part for custom data ?

For the WebGUI part I don't think it's necessary to have multi-languages since English is kind of universel, especially for the target audience of this application

For the custom data, multi-language is already handled. So CVSS is the only thing that is not multi-language. But you can handle that either in the docx template or in the «backend/src/lib/custom-generator.js» file with filters. See the «criteriaFR» filter for example does exactly that for the French language, so in the docx template you only have to write `{value | criteriaFR}` and it will be transated accordingly.

**Comment by noraj** [comment]
> If I understand correctly you are talking about having translation on one part for the WebGUI and on the other part for custom data ?

No I was talking only of translating custom data. But I said there is two option for that, 1) an interface on the WebUI (storing translation in DB) or 2) reading translation from disk from a yml or json file.

> For the custom data, multi-language is already handled. So CVSS is the only thing that is not multi-language. But you can handle that either in the docx template or in the «backend/src/lib/custom-generator.js» file with filters. See the «criteriaFR» filter for example does exactly that for the French language, so in the docx template you only have to write {value | criteriaFR} and it will be transated accordingly.

I'll take a look.
