### ISSUE TITLE
Something went wrong connecting to backend (can't understand the answer you gave for same question already asked)

### ISSUE THREAD

**Issue by emilyanncr** [pwndoc/pwndoc#160]
Yesterday I built pwndoc successfully.  I used it to create my templates and upload vulnerabilities.  I got an entire sample report together to show my boss.  Today I get the error "something went wrong connecting to backend".  Someone has already posted this question.  The reply given was "I guess you are using Firefox: https://pwndoc.github.io/pwndoc/#/installation?id=production".

"For production usage make sure to change the JWT secret in «src/lib/auth.js» and certificates in «ssl» folder" <----

var jwtSecret = config[env].jwtSecret     //Ok so I just put any value I want here??

"Make sure to change the.... certificates in the SSL folder"      // _Change them to what???_

Also the fact you specified Firefox in your answer makes it sound as though the issue does not happen if you use Chrome but I found that is not the case.
I'd greatly appreciate you break down what I should do in basic idiot language.

**Comment by lm-sec** [comment]
Hi, the app should work fine in firefox, this is what I use. Glad you built it successfully though. If you don't mind closing your other issue (https://github.com/pwndoc/pwndoc/issues/152) it would be nice of you. 

Documentation is a bit out of date on the JWT info it looks like. The value you need to change is now located in this file: https://github.com/pwndoc/pwndoc/blob/master/backend/src/config/config.json 

You need to set it a personal unique and random value. Complexity is key here as this key is used to sign the users' sessions. Keeping this key, since it is known, would make anyone be ale to get admin rights on your instance of pwndoc. Since you do not want  that, you need to set it to your own value. 

For the SSL certificate and key, it is used for the encryption of the traffic. This issue with this key is the same as the JWT. Since it is known, anyone could decrypt the client to server messages, even if it is https. Since you want you app's traffic encrypted, you need to set your own SSL certificate and private key. One way to do that is to use openssl like in this stack overflow answer: 
https://stackoverflow.com/questions/10175812/how-to-generate-a-self-signed-ssl-certificate-using-openssl

It is likely that you need to keep the same file names as in the repo for key and cert (server.cert and server.key).

As of your problem to connect to the backend, I can hardly help without any more details. Do you have any stack traces in your logs or in the browser's console that you could share? 

Thanks!

**Comment by BetaMaxHeadroom** [comment]
@emilyanncr, can you please provide the results of `sudo docker ps -a`? That should tell you which docker containers are running, and what the connections look like. 

I ran into a similar issue when connecting to the backend. I _think_ my issue is that the mongodb for production and development both attempt to connect to 127.0.0.1 on port 27017. So, when I attempted to access https://127.0.0.1:8443, I couldn't. Only https://localhost:8081 was accessible. I'm sure that someone more experienced than me has a great workaround for this. However, I only use development at the moment. If this is your issue, I think that you can pull down the appropriate docker containers, and point one of the mongodb containers to use a different port.

**Comment by emilyanncr** [comment]
Thank you so much for responding so quickly @BetaMaxHeadroom @lm-sec 
Yes I noticed that too @lm-sec, so I'm also using development
I rebuilt the package and no have no problem connecting to the backend.  Thanks again guys!
