### ISSUE TITLE
Can't display images

### ISSUE THREAD

**Issue by carhackpils** [pwndoc/pwndoc#172]
Hello,

I tried to create a really simple template only showing the description of a finding with one image.

![image](https://user-images.githubusercontent.com/39593065/129226758-26cd5f12-bf3e-4cbb-895f-d0aed851d549.png)

The my template report looks like this:

```
{#findings}
{title}

{-w:p description}{@text | convertHTML}
{#images}
{%image}
Image 1 – {caption}
{/images}{/description}
{/findings}
```

The output looks like this:
![image](https://user-images.githubusercontent.com/39593065/129227418-f33cd19e-e36a-4661-89c0-e7d30ce9a923.png)

Maybe I'm missing something but I can't display my images.

I've the last version. Thanks !

**Comment by relaxedricky** [comment]
Hey,

I am having trouble seeing where the issue is coming from (maybe not enough coffee yet), can you check to see if anything shows up in the logs:

`docker-compose logs -f pwndoc-backend`

The following looks pretty much the same as what you have but taken from a known to be working template (I know, I know, it looks the same as yours. Humor me please), can you give it a try:

```
{#findings}
{title}
{-w:p description}{@text | convertHTML}
{#images}
{%image}
Image 1 – {caption}
{/images}
{/description}
{/findings}
```

**Comment by carhackpils** [comment]
Same result with your template.

The logs only show this:
```
pwndoc-backend  | user admin joined room 61153e2a8761c600117c63ec
pwndoc-backend  | user admin left room 61153e2a8761c600117c63ec
```

**Comment by yeln4ts** [comment]
How did you upload your image ? Toolbar button, pasting or drag&drop ?

**Comment by carhackpils** [comment]
Sorry I didn't see your message. It was with the toolbar button

**Comment by yeln4ts** [comment]
What type of image was it ? Did you try with different images or different types ?
