### ISSUE TITLE
Possibility to add Category header in report

### ISSUE THREAD

**Issue by KeanuNys** [pwndoc/pwndoc#182]
Since the latest update, findings are categorized within categories and sorted under this category. However, it is not possible to add a header in the report in between every category like this (as far as I know):

---
#### Finding 2
---

**Comment by relaxedricky** [comment]
Just to add to the above, I guess due to category being within findings, there isn't an easy way to have code to dynamically generate sections for each category? @yeln4ts I know you can use the code provided below but need to have a section in the template for each category.

@KeanuNys 
You can add something along the following to a section within your template for each category and delete empty categories as required:

```
Web Application Findings
{#findings} {#category == 'web'} {title} {/category == 'web'} {/findings}
```

**Comment by WhiteWinterWolf** [comment]
This is how it can be done now (I'm not sure whether this syntax existed when the question was originally posted):
```
{#categories}
Current category: {categoryName}
{#categoryFindings}
- Current finding: {title}
{/categoryFindings}
{/categories}
```
