### ISSUE TITLE
Vulnerabilities Summary 

### ISSUE THREAD

**Issue by littlestewart** [pwndoc/pwndoc#22]
Do the Vulns Summary is not suppose to be in first, before the Technical Details ? When i generate the report the Vunls Summary section is the last section of the report is that ok ? And in the Affected Scope table section why i have all the scopes if the vulnerability touch only one host that i have already setup to be the good host target in the technical details section.

Thanks for your help. I really like the web app.

![tempsnip](https://user-images.githubusercontent.com/71742137/94288147-1803da80-ff25-11ea-8f65-a2a79f0b75a3.png)

**Comment by yeln4ts** [comment]
This is just an example template to demonstrate how it works, you can/should change it in any way you want.
Regarding the scope this is because I changed the parameter name and forgot to update the default template, thanks for pointing it out, I'll fix it soon. In the meantime you can copy the text from the finding table it will be the same.
