### ISSUE TITLE
CVSS Score Audit sorting

### ISSUE THREAD

**Issue by pandabottle** [pwndoc/pwndoc#231]
By selecting CVSS Score and descending as the default vulnerability category, I assumed it would specify the highest CVSS Score as 1 in the identifier command. However, when generating an audit, it seems that the identifier command is related to when the vulnerability was added.

This means even if you add a lower CVSS Score after a higher one, the identifier states the lower CVSS score as the higher number. Is there a fix for this or is there a different function? It seems the audit does auto sort it, but does not generate it in report.

**Comment by pandabottle** [comment]
In case my request was hard to understand, here is a guided walk through.

1. On custom data -> Vulnerabilities categories, I have set the default as CVSS Score and sort order by "descending"
<img width="552" alt="CVSS default" src="https://user-images.githubusercontent.com/79141006/147900078-8ad995e8-70a0-410a-98d0-e1349bcd0134.PNG">

2. When creating a new audit, regardless of when I select my vulnerability, it autosorts it according to the CVSS Score, as shown.
<img width="200" alt="CVSS auto sort" src="https://user-images.githubusercontent.com/79141006/147900173-5029c6f6-36ab-42bb-91fa-cfb0d7e004ae.PNG">

3. However, when generating the audit, the identifier per vulnerability is as shown.
<img width="701" alt="CVSS vulnerabilities report" src="https://user-images.githubusercontent.com/79141006/147900182-f8aec446-f434-414c-a544-959547797fc2.PNG">

This is not the ideal output, since I assume pwndoc will autosort it. This is what I assumed would've been the expected output.
<img width="690" alt="expectation" src="https://user-images.githubusercontent.com/79141006/147900205-e41e2178-4b63-4285-af92-c459e957259c.PNG">

**Comment by yeln4ts** [comment]
Hello,

The ID that is automatically generated is related to the creation order. It was made like that so that if you modify your audit, IDs will stay the same. To better picture it, imagine you have a finding with severity `High` and after multiple reviews process it is decided to change it to `Medium`, then this finding will keep the same ID and it will stay consistent throughout multiple report versions.
If you want an even more consistent process you could add a custom ID field for all your vulnerabilities and use it instead so that your findings will have the same ID in all your reports.

**Comment by pandabottle** [comment]
Thanks, I have a better understanding of its functionality right now. I have used customID and it does work as intended, though I was hoping there would be some variable that would help autogenerate to remove manually typing the order. Not a big issue, since customID does the trick.

Closing this issue since the problem is solved.
