### ISSUE TITLE
Template Error: The scope parser for the tag description | convertHTML failed to execute

### ISSUE THREAD

**Issue by RaymondTheBastard** [pwndoc/pwndoc#27]
I have been trying to build up a custom template using the docxtemplater guide but I'm now stuck on this error.
![image](https://user-images.githubusercontent.com/72358747/95026030-3e90e680-0686-11eb-9e02-b6ef11721e28.png)

This is the template;
![image](https://user-images.githubusercontent.com/72358747/95026060-7730c000-0686-11eb-951f-6a22e32e90f0.png)

Any ideas on what could be broken here? seems like it is an error with the parser.

**Comment by yeln4ts** [comment]
You should take a look at the latest Docx Template available. Description and Remediation must be used the same way as poc (since you can have images now). Also for the affected hosts field is now «affected» instead of «scope» to avoid confusion with the scope of the audit.
You can also take a look at the documentation: https://pwndoc.github.io/pwndoc/#/docxtemplate. You will find some information about different fields and how to use in the template.
