### ISSUE TITLE
Environmental/Temporal Scores

### ISSUE THREAD

**Issue by thegeekkid** [pwndoc/pwndoc#296]
Is there documentation on the objects for temporal or environmental scores anywhere?  I'm trying to add them to a report template such as {cvssObj.MAV} (I've also tried {cvssv3.MAV}; but each time I try to upload the template, it returns a internal error when I try to download the audit report.

As an example:
![image](https://user-images.githubusercontent.com/8616594/161641000-de7e891a-60f6-4e7d-8e3a-b32ca8b9061f.png)

(In the example above, I tried going variable by variable and taking out the headers thinking maybe it was just one throwing it off)

Thanks for the amazing work you do on this project!

**Comment by relaxedricky** [comment]
Hi,

The fact you are getting an internal error suggests you have an issue within your report template.

I can confirm `{cvssObj.MAV}` and `{cvssObj.RC}` are valid syntax and worked in my quick test. If you had set something that wasn't valid, you work normally just get an `undefined` output in its place.

I would recommend watching the backend log when trying to create the report, this should give you a better idea of where the issue is within your report template:

`
docker-compose -f backend/docker-compose.dev.yml logs -f pwndoc-backend
`
