### ISSUE TITLE
Types vs Categories - Which to use where

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc/pwndoc#321]
Hi @yeln4ts,

I just wanted to confirm something. In the current docs, you have the following:

> Vulnerability Types
> Vulnerability Types represent the nature of a Vulnerability. They are multilingual.

```
Example
English
    Name: Wireless,
    Name: Mobile Application
```

and

> Vulnerability Categories
> Vulnerability Categories are used to categorize a Vulnerability.

```
Example
Name: Nessus Scan
```

From reading the above, I would assume when I create a new vulnerability in Pwndoc I should be setting the type to web if it was a web application vulnerability. Makes sense.

What feels a little confusing is the functionality to generate docx's based on dynamic categories. I feel like being able to add the following in a template:

```
{#categories}
{categoryName} (Header)
{#categoryFindings}
... same thing as before ...
{/categoryFindings}
{/categories}
```

This has resulted in a lot of people setting categories to things like Web, API and Mobile and using this to break up an assessment that has more than one section to it. Whereas from the docs and past replies from you in raised issues, people are directed to not use categories for this but instead use types.

Do types have the same functionality  to create a docx dynamically  without having to use something along the lines of:

`{#findings} {#type == 'web'} {title} {/type == 'web'} {/findings}`

I am aware I could continue to use my template as I currently am, categories being used to break up sections (e.g. Web and Mobile) of the test, however, I just wanted to confirm the above, as I guess you could make changes at a later date based on your intended use for each item that could result in a template rewrite being needed.

**Comment by yeln4ts** [comment]
Hi,

I understand how this can be confusing.

Initially there were only Vulnerability types but I wanted to add a way to structure an Audit with the ability to handle custom fields so I added Categories.

I have the goal to add another layer to handle multi-phase audits so that you will have Audit > Phase > Category > Vuln Type

To answer your question about dynamic generation using vulnerability types, it is not possible now but there is this PR #281 that I have to review that add multiple filters with specifically the `groupBy` one that could be used to do the same thing as categories.

**Comment by relaxedricky** [comment]
Thanks for explaining your goal of adding a new layer for "multi-phase audits".

I will also keep an eye out for the PR being merged.
