### ISSUE TITLE
(Vulnerability) Username enumeration via response timing

### ISSUE THREAD

**Issue by Astaruf** [pwndoc/pwndoc#381]
It is possible to enumerate users registered in PwnDoc (tested on 0.5.3 - 2022-07-19 and previous versions) observing the web server response timing.
For example, let's suppose these users were registered on PwnDoc:

![Schermata del 2022-10-06 23-22-56](https://user-images.githubusercontent.com/43656486/194424548-0684d566-f28b-40b2-ab9c-cb3b11bf0173.jpg)

By performing a brute force dictionary attack, a defined list of users can be provided via login POST request to detect the server's response time.

![Schermata del 2022-10-06 23-35-03](https://user-images.githubusercontent.com/43656486/194425746-0642cf93-973c-40ca-900b-a1eac7c9ae6c.png)

All the valid users can be discovered by a potential attacker checking if the response time to the login request is long. For not-existing users we can see a shorter response time.

The attack success depends higly on the stability of the server and the Internet connection between hosts. In any case, in order to apply a remediation, it is advisable to add a timing delay to balance the response timing for each login request.

Let me know if I can help you in any way so, once fixed I would like to get a CVE from mtre.org

**Comment by Astaruf** [comment]
A CVE-ID has been reserved by Mitre.org for this vulnerability CVE-2022-44022.

**Comment by MaxNad** [comment]
In the future, I would advise following the newly created security policy as publicly disclosing a vulnerability with a full proof on concept without contacting the project maintainers, providing a PR with a solution and/or using the GitHub private disclosure feature is not the most responsible way to go about it.

That being said, thank you for caring about the security of PwnDoc.

This issue was fixed in commit bd8bded
