### ISSUE TITLE
updates to findings not being applied

### ISSUE THREAD

**Issue by AnotherWayIn** [pwndoc/pwndoc#446]
is it just me as i cannot apply any proposed updates to the vulnerabilies?
When i add some content to an issue, i click propose update in database, then goto the finding with the update and click accept but it doesn't show the new content

**Comment by MaxNad** [comment]
When proposing a finding, the view shows the difference between the original (left) and the updated.finding (right).

When clicking "Apply", the content on the left will be saved. To fully apply the changes, to have to copy what you would like to keep from the right to the left (since the admin may not want to merge everything as-is).

I admin that this is not the most intuitive way to operate. I am open to suggestions in ways to improve this workflow

**Comment by AnotherWayIn** [comment]
Thanks! I thought clicking apply would accept all the right side changes into the left. That's fine as long as i know. I guess it could explain this better, but at least we have more control now over what gets changed rather than the accept all approach
