### ISSUE TITLE
Enhancement Request / Directions

### ISSUE THREAD

**Issue by int3ring0** [pwndoc/pwndoc#46]
First thanks for this great pice of software. It works stable, template editing is easy. Safes me a lot of time as a pentester.

Is it difficult to create Findings from xml ? I would love to import Nexpose, Metasploit and BurpSuit findings into the report.
Where do I have to start, while willing to implement it by my self?

Thanks in advance,
Thorsten

**Comment by yeln4ts** [comment]
I think it depends on what kind of data is present in the XML. Theoretically, it would be doable since the creation of a finding is just an API request, but it would have to match with vulnerability fields in pwndoc. It would also need a way to select findings you really want in order to reject false positives.

Personally, I wouldn't go this way since the goal is to have a personalized report that adds value to your pentest with verified findings, and not automatically generate reports from scanners.
