### ISSUE TITLE
Template Customization

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [pwndoc/pwndoc#5]
Hi, 

Thank you so much for creating this tool. I'm trying to get it to work based on a different template that I was using. But, it doesn't seem to work very well for me. Would you happen to know where I can look into any debug info?

**Comment by yeln4ts** [comment]
You can check the docxtemplater documentation or the default template provided to better understand how it works.
Also for debuging use the docker-compose dev file. The report generation happens in «pwndoc/backend/src/lib/report-generator.js» in the «generateDoc» function.
My advice would be to use Microsoft word for building the template docx, and also to start without any tag and add them one by one to see where the problem is

**Comment by BetaMaxHeadroom** [comment]
I figured out part of the issue. There are still a few things that I need to work through. But, I might be able to do the rest in Word. I learned something that I hope to pass along. 

DO NOT UPDATE THE TABLE OF CONTENTS IN YOUR TEMPLATE. ONLY UPDATE IT AFTER YOUR REPORT HAS BEEN GENERATED. 

Since I lack any degree of creativity, all I need to do now is figure out who to bribe to make these reports blow some minds. You are the best. Thank you for all of your help.
