### ISSUE TITLE
CVSS severity in French

### ISSUE THREAD

**Issue by Liodeus** [pwndoc/pwndoc#50]
I'm trying to make a custom generator to translate cvssSeverity to french. But everytime I get this error : The scope parser for the tag "cvssSeverity | cvssSeverityFR " failed to compile.

```js
expressions.filters.cvssSeverityFR = function(input) {
    var pre = '<w:p><w:r><w:t>';
    var post = '</w:t></w:r></w:p>';
    var result = "Non défini"

    if (input === "Low") result = "Faible"
    else if (input === "Medium") result = "Moyenne"
    else if (input === "High") result = "Elevé"
    else if (input === "Critical") result = "Critique"

    // return pre + result + post;
    return result;
}
```

Here's what I tried. Could you help me please ?

And I have a question with the nmap import, when I do a scan I have the "version" of the services, but when imported, they appears as "Unknown", why is that ? (nmap command used : nmap -oX test.xml test.fr -sV -v).

**Comment by yeln4ts** [comment]
Can you show the part where it's called in your template ?

Regarding the nmap import I would have to take a closer look, I coded that a loooong time ago

**Comment by Liodeus** [comment]
I'm calling it like so in the report template : 

![Capture](https://user-images.githubusercontent.com/26687848/100466777-c668ff00-30d1-11eb-8753-926646be5417.PNG)

**Comment by yeln4ts** [comment]
Sorry I forgot to answer you.
The function should work. 
What I can comment on your template srceenshot is that {@cvssColor} should be alone on a paragraph, but the error should be different. And anyway you can achieve what you want by replacing {cvssSeverity | cvssSeverityFR} by the result directly since you are checking the condition before (also the {@cvssColor} is not necessary since you define the color in the template). So that would give:
{#findings}{#cvssSeverity == 'High'}Élevé                  {title}                 ...
