### ISSUE TITLE
Add custom_field for older audits/vulnerabilities

### ISSUE THREAD

**Issue by Nicodoxia** [pwndoc/pwndoc#540]
When creating a new custom field for audits or vulnerabilities, the field doesn't appear in older cases. For example, I created two new custom fields for my audits, but on different dates. As a result, my newer audits include both fields:
![image](https://github.com/user-attachments/assets/e809e883-9043-4d34-8254-19aeea5281ec)

While older audits just have one of those 2 fields:
![image](https://github.com/user-attachments/assets/5c0195b5-d687-49d5-843c-d34c3b4bbcfb)

It would be nice if new fields could be "migrated" through all audits and vulnerabilities.
Nowadays, I have to recreate every vulnerability to achieve setting my new field.

I'm now running release 0.5.3 but it seems to still be the same on latest commit on main.

**Comment by yeln4ts** [comment]
This is the expected behavior as I made the decision that an audit is fixed once created. The goal was to be sure that once an audit is done you know that it won't be changed afterwards (adding or removing custom fields).
Regarding Vulnerabilities if you add a custom field it will be displayed so you don't have to recreate vulnerabilities.

**Comment by Nicodoxia** [comment]
Thanks for the answer! 

So, as a workaround, I'll need to create new audits to include those fields in the newer ones?

**Comment by yeln4ts** [comment]
Yes they will be included in new audits only
