### ISSUE TITLE
Too Large File to upload

### ISSUE THREAD

**Issue by x30r** [pwndoc/pwndoc#67]
I created the entire template and it was working fine. Today, I clone the updated code base from github but this time while importing the template showed me this error. 

There is this error prompt response from the server.
 
![upon click](https://user-images.githubusercontent.com/13844523/104812121-35d3b300-5826-11eb-9d47-58ea56a24ba8.png)

Checking the console, I got to know that the request I made was not correct. Check the response:

![res](https://user-images.githubusercontent.com/13844523/104812137-4f74fa80-5826-11eb-881e-70bc7632b3a9.png)
 
I tried to manually check the upload limit is 10mb yet this is something which looks really weird.
Here, the default format is working fine and I assure that the template do not have any parsing issues.

I that there are changes made in the default template but that doesn't make any difference while parsing it  to the server as a new ID column is added and nothing apart from that. All the notations are same.

Am I doing something wrong?

**Comment by acap4z** [comment]
The same happened to me when trying to upload a custom template that was somewhat large (5MB). The problem comes with the Nginx proxy configuration in the pwndoc-frontend container, which is not set and therefore it takes the default value (1MB).

As a workaround, you can fix this by adding this parameter to Nginx and then restarting containers:
`docker exec -it pwndoc-frontend /bin/sh`
`echo 'client_max_body_size 20m;' > /etc/nginx/conf.d/max_upload.conf`
`exit`
`docker-compose restart`

Hope they can include a fix to avoid this.
